services:
  app:
    container_name: Flask
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV: development
